### ISSUE TITLE
Demo code not working

### ISSUE THREAD

**Issue by attiliovaccaro** [ojarva/davis-weatherlink-scraper#1]
The code reported in the Usage section is not correct.

The scraper declaration

`scraper = WeatherLink()`

fails.

It should be:
`scraper = davis_weatherlink_scraper.WeatherLink()`

or the import should be changed.

**Comment by ojarva** [comment]
Thanks! Fixed, I'll fix tests (or code, I don't know which) and release a new version to packages.python.org.
